Практична робота №1 з предмету: "Машине Навчання".
Студента: Коленика Максима Максимовича.
Варіант 9

In [1]:
import numpy as np

Завдання 1. Створіть одновимірний масив (вектор) з числами Фібоначчі, де кожне число дорівнює сумі двох попередніх, та виведіть його значення.

In [ ]:
n = 10
fibonacci = np.zeros(n, dtype=int)
fibonacci[0] = 0
fibonacci[1] = 1

for i in range(2, n):
    fibonacci[i] = fibonacci[i - 1] + fibonacci[i - 2]
print(fibonacci)

[ 0  1  1  2  3  5  8 13 21 34]


Завдання 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями експонент n^2 для кожного натурального числа n, починаючи з 1, та виведіть його значення.

In [ ]:
n = 3
matrix = np.zeros((n, n), dtype=float)

for i in range(n):
    for j in range(n):
      matrix[i][j] = np.exp((i * n + j + 1) ** 2)
print(matrix)

[[2.71828183e+00 5.45981500e+01 8.10308393e+03]
 [8.88611052e+06 7.20048993e+10 4.31123155e+15]
 [1.90734657e+21 6.23514908e+27 1.50609731e+35]]


Завдання 3. Створіть масив розміром 6x6, заповніть його випадковими дійсними числами від -1 до 1 та виведіть його значення.

In [ ]:
n = 6
matrix = np.random.uniform(-1, 1, size=(n, n))
print(matrix)

[[-0.22386315  0.1854952   0.02307972 -0.31620493  0.19417185  0.90206703]
 [ 0.00694308  0.87107414  0.30018486 -0.12741845  0.57473565  0.89146461]
 [-0.00936769  0.38410419 -0.25085779  0.79484221 -0.35274415 -0.11550148]
 [ 0.59215909  0.15481757  0.71415154 -0.24349712 -0.33205207 -0.7856468 ]
 [ 0.41669218 -0.07150562  0.96749766  0.46375226 -0.33354365 -0.92430851]
 [-0.8013084   0.69607679  0.83076793 -0.05537821  0.82413246 -0.92734953]]


Завдання 4.Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть середнє геометричне всіх елементів.

In [3]:
array = np.random.rand(3, 3)
geometric_mean = np.prod(array) ** (1 / (array.size))
print("Масив:")
print(array)
print("Середнє геометричне всіх елементів:", geometric_mean)

Масив:
[[0.01295637 0.07683133 0.8132187 ]
 [0.6978157  0.87631562 0.90655702]
 [0.03301897 0.565936   0.94812703]]
Середнє геометричне всіх елементів: 0.27125661299553966


Завдання 5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними числами від -5 до 5 та виконайте на них поелементні операції додавання, віднімання та множення.

In [5]:
array1 = np.random.uniform(-5, 5, 6)
array2 = np.random.uniform(-5, 5, 6)

print("Масив 1:")
print(array1)
print("Масив 2:")
print(array2)

addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

print("Результат додавання:")
print(addition_result)
print("Результат віднімання:")
print(subtraction_result)
print("Результат множення:")
print(multiplication_result)

Масив 1:
[ 2.81134463  4.98235843 -4.61630687  2.37485137  3.59213852  4.29236019]
Масив 2:
[-0.37324767 -3.17133018  4.59237364 -4.92306146 -4.14586715 -1.74885747]
Результат додавання:
[ 2.43809697  1.81102826 -0.02393323 -2.54821008 -0.55372863  2.54350272]
Результат віднімання:
[ 3.1845923   8.15368861 -9.20868051  7.29791283  7.73800567  6.04121766]
Результат множення:
[ -1.04932783 -15.80070365 -21.19980599 -11.69153927 -14.89252909
  -7.50672618]


Завдання 6. Створіть два вектори розміром 8, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.

In [6]:
vector1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
vector2 = np.array([8, 7, 6, 5, 4, 3, 2, 1])

scalar_product = np.dot(vector1, vector2)

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Скалярний добуток векторів:", scalar_product)

Вектор 1: [1 2 3 4 5 6 7 8]
Вектор 2: [8 7 6 5 4 3 2 1]
Скалярний добуток векторів: 120


Завдання 7. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та перемножте їх між собою.

In [7]:
matrix1 = np.random.randint(1, 21, (3, 2))
matrix2 = np.random.randint(1, 21, (2, 4))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

result_matrix = np.dot(matrix1, matrix2)

print("Результат перемноження матриць:")
print(result_matrix)

Матриця 1:
[[ 3 16]
 [11 13]
 [ 1 15]]
Матриця 2:
[[ 6  2  4 14]
 [10 13 18  2]]
Результат перемноження матриць:
[[178 214 300  74]
 [196 191 278 180]
 [156 197 274  44]]


Завдання 8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

In [8]:
matrix = np.random.randint(1, 16, (2, 2))

print("Початкова матриця:")
print(matrix)

try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Матриця не має оберненої матриці (детермінант дорівнює нулю).")

Початкова матриця:
[[10  9]
 [15 10]]
Обернена матриця:
[[-0.28571429  0.25714286]
 [ 0.42857143 -0.28571429]]


Завдання 9. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 7 до 15 та транспонуйте її.

In [9]:
matrix = np.random.randint(7, 16, (3, 3))

print("Початкова матриця:")
print(matrix)

transposed_matrix = np.transpose(matrix)

print("Транспонована матриця:")
print(transposed_matrix)

Початкова матриця:
[[10  8 10]
 [ 7 10 10]
 [ 7 12 14]]
Транспонована матриця:
[[10  7  7]
 [ 8 10 12]
 [10 10 14]]


Завдання 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть елементи отриманого вектору, які менше середнього значення вектору.

In [10]:
matrix = np.random.rand(3, 4)

print("Початкова матриця:")
print(matrix)

vector = np.random.randint(1, 11, 4)

print("Початковий вектор:")
print(vector)

mean_value = np.mean(vector)
print("Середнє значення вектору:", mean_value)

less_than_mean = vector[vector < mean_value]
print("Елементи вектору менше середнього значення:", less_than_mean)

Початкова матриця:
[[0.22836023 0.74871296 0.67615064 0.86971707]
 [0.5865229  0.41586602 0.62367953 0.49620681]
 [0.3197499  0.62061093 0.28978295 0.2706803 ]]
Початковий вектор:
[2 7 9 9]
Середнє значення вектору: 6.75
Елементи вектору менше середнього значення: [2]


Завдання 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток вектора на матрицю.

In [12]:
matrix = np.random.rand(2, 3)

print("Початкова матриця:")
print(matrix)

vector = np.random.randint(1, 11, 3)

print("Початковий вектор:")
print(vector)

product = np.dot( matrix, vector )

print("Добуток вектора на матрицю:")
print(product)

Початкова матриця:
[[0.70341772 0.67556685 0.67228571]
 [0.28413028 0.59026909 0.80233197]]
Початковий вектор:
[4 3 5]
Добуток вектора на матрицю:
[8.20179996 6.91898825]


Завдання 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму всіх елементів обох матриць.

In [13]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

sum_of_matrices = matrix1 + matrix2

print("Сума матриць:")
print(sum_of_matrices)

total_sum = np.sum(sum_of_matrices)

print("Загальна сума всіх елементів:", total_sum)

Матриця 1:
[[3 7]
 [5 7]]
Матриця 2:
[[4 5]
 [5 4]]
Сума матриць:
[[ 7 12]
 [10 11]]
Загальна сума всіх елементів: 40


Завдання 13. Створіть дві матриці розміром 10x10, заповніть їх випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть їх добуток.

In [15]:
matrix1 = np.random.uniform(-2, 2, (10, 10))
matrix2 = np.random.uniform(-2, 2, (10, 10))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

product_matrix = np.dot(matrix1, matrix2)

print("Добуток матриць:")
print(product_matrix)

Матриця 1:
[[-0.42892744  0.23983227 -1.59931496  0.20972018  1.73432108 -0.00283576
  -1.43684907 -1.61297093 -1.74957016 -0.83465134]
 [ 1.23827637 -1.75315163 -0.80510654 -1.60795469 -0.74797824 -0.01728381
   0.95315205 -0.23767561 -0.57117627  1.57075738]
 [-0.67074631 -1.19644796 -0.42614825 -0.44428724  1.05816813  1.05833559
   1.7064833  -1.5873524   1.94130802 -0.86642278]
 [ 1.68959122 -1.78513708 -1.13582747  1.73729722  0.56090176  1.54824712
   0.74633786  0.07217035 -1.13248595  0.75578835]
 [-0.16855315 -1.51050754  1.37477775 -0.44526655  0.51278755 -1.33516437
  -0.73462609  1.73999203 -0.29903548 -1.11239846]
 [-1.31793256 -1.56219527  1.51578905 -0.42738049 -0.03741987  1.19520622
  -1.47069513  1.02891435  0.28599899  0.71751352]
 [ 1.63458368  1.10341683  0.81760201 -0.68374706  0.93323532  0.12838234
  -0.88984912  1.60825237 -0.8881362  -1.33858095]
 [-0.1335806  -1.57376523 -0.55428765  0.24317918  1.23966943  1.24354983
   1.0682496   1.340565   -0.83711906 -0

Завдання 14. Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть середнє арифметичне значення елементів матриці.

In [16]:
matrix = np.random.uniform(-1, 1, (7, 7))

print("Початкова матриця:")
print(matrix)

mean_value = np.mean(matrix)

print("Середнє арифметичне значення елементів матриці:", mean_value)

Початкова матриця:
[[ 0.27281393 -0.20207277 -0.39262917  0.04528016  0.96505771  0.13361381
   0.35823307]
 [ 0.68953537  0.08517552  0.88495618  0.52705597 -0.64390526  0.97906473
   0.31673626]
 [ 0.93378699  0.81510217  0.86914639 -0.42039344  0.56097718 -0.87946911
  -0.56302536]
 [-0.22349277  0.09665049 -0.09826462  0.68034049 -0.09723682 -0.81938657
  -0.55386254]
 [-0.71970898  0.72661212  0.28548439  0.36498726  0.30596413 -0.35446709
   0.76296874]
 [-0.9477647  -0.42303789 -0.59071655 -0.57030222 -0.48478135 -0.83954465
  -0.83138299]
 [ 0.25455089  0.93932317 -0.0765122  -0.10700093  0.0332449  -0.73493127
  -0.44637793]]
Середнє арифметичне значення елементів матриці: 0.01768152702963664


Завдання 15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму квадратів елементів кожного рядка матриці.

In [17]:
matrix = np.random.rand(3, 3)

print("Початкова матриця:")
print(matrix)

row_sums = np.sum(matrix**2, axis=1)

print("Сума квадратів елементів кожного рядка:")
print(row_sums)

column_vector = row_sums.reshape(-1, 1)

print("Вектор-стовпчик із сумами квадратів елементів кожного рядка:")
print(column_vector)

Початкова матриця:
[[0.41394989 0.15686764 0.46560764]
 [0.07093143 0.02952585 0.99484941]
 [0.06544937 0.58608647 0.66040051]]
Сума квадратів елементів кожного рядка:
[0.41275244 0.99562839 0.7839098 ]
Вектор-стовпчик із сумами квадратів елементів кожного рядка:
[[0.41275244]
 [0.99562839]
 [0.7839098 ]]
